name: intorrent_example
description: Example app for the InTorrent Flutter plugin.
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intorrent:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^3.0.0

flutter:
  uses-material-design: true
